### ISSUE TITLE
Add mypy and deptry as pre-commit hooks

### ISSUE THREAD

**Issue by aaccioly** [fpgmaas/cookiecutter-poetry#81]
Currently mypy is not running automatically (neither locally nor as part of GitHub's pipeline).

A user has to manually run:

```bash
make check
```

If he wants to trigger type checking.

deptry runs as part of the pipeline, but, IMO, it should be also run as part a pre-commit hook as catching dependency problems after they have been introduced is not great .

### Proposed solution

Add both tools to pre-commit 

### Additional context

I've just recently adopted cookiecutter-poetry (thanks a million for it) and butchered some type hints.

I was under the impression that mypy was running automatically but unfortunately this wasn't the case. Later I've realised that there's a dedicated make target for linting, but had to read the Makefile to find it out (see #79).

As both mypy and deptry are able to run very fast I would have no problem running both of them on every commit.

**Comment by fpgmaas** [comment]
Thanks for raising the issue! Sorry that this flaw in cookiecutter-poetry allowed you to butcher your typehints. I think the issue here is that `mypy` is triggered in the tox tests, since it should be verified for the different versions of Python; see [here](https://github.com/fpgmaas/cookiecutter-poetry-example/blob/main/tox.ini#L18) in the example repository. I assume that you have tox disabled, which causes the `mypy` checks to be skipped. 

This is of course not the desired behavior. An approach to solve this is to run the `mypy` tests in tox when `tox="y"`, and in the `main.yml` workflow otherwise.

Alternatively, we could add the mypy check to `make check`, and run `make check` in the `main.yml` workflow. This does mean that for one Python version, the mypy checks are ran twice, but it is easier to implement and perhaps more clear to users of the repository.

I am not a big fan of adding both tools to pre-commit, since that also includes it's own set of issues and workarounds, see e.g. [here](https://jaredkhan.com/blog/mypy-pre-commit).

On the other hand, deptry should always be run within the main workflow; see [here](https://github.com/fpgmaas/cookiecutter-poetry-example/blob/main/.github/workflows/main.yml#L28).

Curious for your thoughts on the above! I will try to pick this up over the weekend.

**Comment by fpgmaas** [comment]
Thanks for your elaborate and clear answer! I think this also a very good project set-up that I could see myself using. However, I am a bit hesitant to apply this way of working to `cookiecutter-poetry`, since running all tools against all files on every change may not work very well for everyone. For example, I can see this becoming an issue for large Python projects. There might also just be a bit of hesitancy from my side since I have not battle-tested this approach myself :) 

So if you think the following solution is also okay;

> Alternatively, we could simply runmake check in the main.yml workflow. This does mean that for one Python version, the mypy checks are ran twice, but it is easier to implement and perhaps more clear to users of the repository.

I'd prefer to implement that.

However, if you have a fork of the repo adapted to your approach, I'd be happy to mention it in the README.md to make other users aware of the alternative!

**Comment by aaccioly** [comment]
> I can see this becoming an issue for large Python projects. There might also just be a bit of hesitancy from my side since I have not battle-tested this approach myself

This if fair enough. I assumed that this would be case (and hence why I wrote a long comment instead of a PR :)).

> I'd prefer to implement that.

I think that this would be the next best alternative yes. The tradeoff is that folks doing trunk base development would still need to run mypy manually (or find out about problems after commiting - which isn't ideal). However, given the choice between running fast but semi-broken mypy as a pre-commit plugin vs running it properly in the CI/CD pipeline I guess that your instinct is correct.

>  if you have a fork of the repo

I've implemented all of the above on a fully initialized repo instead of a fork of the Cookiecutter template. I also don't think that the changes are significant enough to deserve their own fork.
Tell you what, if you are really interested in the approach described above (as in, not only trying to be nice to me🤣) what do you think about creating a branch? Say `shift-left-linters`. I'll submit a PR to it and we'll try to keep it up-to-date with main for a while. If it ends up working well, we can later think of merging it to main hidden behind a non-default flag. What do you think?

**Comment by fpgmaas** [comment]
@aaccioly I have thought about the proposal above; and even though I think it can definitely be useful for some users, I prefer to not add it as a non-default flag to this repo. The main reason for that is that I find it difficult to properly test all the combinations of configurations (which also caused this issue), which is why I keep this repository simple and a a bit opinionated and I try to limit the configuration possibilities. Adding this feature will double the number of combinations to be tested, and I don't think I can support that this keeps working with any new changes going forward.

I hope that is okay with you! 

If this issue gains more traction in the future, or more people voice their demand for such a configuration, I'd be happy to reconsider.
